/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetsUploadRouteImport } from './routes/datasets.upload'
import { Route as DatasetsIdRouteImport } from './routes/datasets.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsUploadRoute = DatasetsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DatasetsRoute,
} as any)
const DatasetsIdRoute = DatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DatasetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/datasets/upload': typeof DatasetsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/datasets/upload': typeof DatasetsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/datasets/upload': typeof DatasetsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/chat'
    | '/dashboard'
    | '/datasets'
    | '/history'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/datasets/$id'
    | '/datasets/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/chat'
    | '/dashboard'
    | '/datasets'
    | '/history'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/datasets/$id'
    | '/datasets/upload'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/chat'
    | '/dashboard'
    | '/datasets'
    | '/history'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/datasets/$id'
    | '/datasets/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DatasetsRoute: typeof DatasetsRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/upload': {
      id: '/datasets/upload'
      path: '/upload'
      fullPath: '/datasets/upload'
      preLoaderRoute: typeof DatasetsUploadRouteImport
      parentRoute: typeof DatasetsRoute
    }
    '/datasets/$id': {
      id: '/datasets/$id'
      path: '/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof DatasetsIdRouteImport
      parentRoute: typeof DatasetsRoute
    }
  }
}

interface DatasetsRouteChildren {
  DatasetsIdRoute: typeof DatasetsIdRoute
  DatasetsUploadRoute: typeof DatasetsUploadRoute
}

const DatasetsRouteChildren: DatasetsRouteChildren = {
  DatasetsIdRoute: DatasetsIdRoute,
  DatasetsUploadRoute: DatasetsUploadRoute,
}

const DatasetsRouteWithChildren = DatasetsRoute._addFileChildren(
  DatasetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DatasetsRoute: DatasetsRouteWithChildren,
  HistoryRoute: HistoryRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
